name: Test

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Test
        run: dotnet vstest C:\Users\Quinten\source\repos\Questmaker\QuestMakerTests\bin\Debug\QuestMakerTests.dll
